import {
  assertEquals,
  assertRejects,
  assertThrows,
} from "https://deno.land/std@0.224.0/assert/mod.ts";
import {
  capturedImageFromBytes,
  imageDimensions,
  readBounded,
  validateMediaUrl,
} from "./bounded_media.ts";

Deno.test("bounded media only trusts controlled HTTPS hosts", () => {
  assertEquals(
    validateMediaUrl("https://pbs.twimg.com/media/test.png"),
    "https://pbs.twimg.com/media/test.png",
  );
  assertThrows(
    () => validateMediaUrl("http://127.0.0.1/file.png"),
    Error,
    "invalid_media_url",
  );
  assertThrows(
    () => validateMediaUrl("https://example.com/file.png"),
    Error,
    "untrusted_media_host",
  );
});

Deno.test("generated bytes receive the same bounded validation", async () => {
  const bytes = new Uint8Array(24);
  const view = new DataView(bytes.buffer);
  view.setUint32(0, 0x89504e47);
  view.setUint32(4, 0x0d0a1a0a);
  view.setUint32(16, 64);
  view.setUint32(20, 64);
  const image = await capturedImageFromBytes(
    bytes,
    "image/png",
    "generated:test",
  );
  assertEquals(image.width, 64);
  assertEquals(image.height, 64);
  assertEquals(image.sha256.length, 64);
});

Deno.test("bounded stream aborts before unbounded buffering", async () => {
  const stream = new ReadableStream<Uint8Array>({
    start(controller) {
      controller.enqueue(new Uint8Array(4));
      controller.enqueue(new Uint8Array(4));
      controller.close();
    },
  });
  await assertRejects(() => readBounded(stream, 7), Error, "media_too_large");
});

Deno.test("PNG dimensions are parsed from the bounded header", () => {
  const bytes = new Uint8Array(24);
  const view = new DataView(bytes.buffer);
  view.setUint32(0, 0x89504e47);
  view.setUint32(4, 0x0d0a1a0a);
  view.setUint32(16, 512);
  view.setUint32(20, 256);
  assertEquals(imageDimensions(bytes, "image/png"), {
    width: 512,
    height: 256,
  });
});

Deno.test("external image URL validation blocks SSRF-shaped hosts", async () => {
  const { validateExternalImageUrl } = await import("./bounded_media.ts");
  assertEquals(
    validateExternalImageUrl("https://example.com/logo.png"),
    "https://example.com/logo.png",
  );
  for (
    const bad of [
      "http://example.com/logo.png",
      "https://user:pass@example.com/a.png",
      "https://example.com:8443/a.png",
      "https://localhost/a.png",
      "https://api.localhost/a.png",
      "https://box.local/a.png",
      "https://service.internal/a.png",
      "https://router.lan/a.png",
      "https://nas.home.arpa/a.png",
      "https://intranethost/a.png",
      "https://127.0.0.1/a.png",
      "https://10.0.0.1/a.png",
      "https://169.254.169.254/latest/meta-data",
      "https://[::1]/a.png",
      "https://0x7f000001/a.png",
      "https://2130706433/a.png",
      "not a url",
    ]
  ) {
    let threw = false;
    try {
      validateExternalImageUrl(bad);
    } catch {
      threw = true;
    }
    assertEquals(threw, true, `expected rejection for ${bad}`);
  }
});
