/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SecretpanelRouteImport } from './routes/secretpanel'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LaunchesRouteImport } from './routes/launches'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BugsRouteImport } from './routes/bugs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentApiRouteImport } from './routes/agent-api'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NftsIndexRouteImport } from './routes/nfts.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as TelegramVerifyRouteImport } from './routes/telegram.verify'
import { Route as TelegramAuthRouteImport } from './routes/telegram.auth'
import { Route as SmsAuthRouteImport } from './routes/sms.auth'
import { Route as NftsCollectionIdRouteImport } from './routes/nfts.$collectionId'
import { Route as CoinMintRouteImport } from './routes/coin.$mint'
import { Route as CliAuthRouteImport } from './routes/cli.auth'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthBannedRouteImport } from './routes/auth.banned'
import { Route as AuthenticatedTerminalRouteImport } from './routes/_authenticated.terminal'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppWalletRouteImport } from './routes/_authenticated.app.wallet'
import { Route as AuthenticatedAppTerminalRouteImport } from './routes/_authenticated.app.terminal'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated.app.settings'
import { Route as AuthenticatedAppSchedulerRouteImport } from './routes/_authenticated.app.scheduler'
import { Route as AuthenticatedAppPoolsRouteImport } from './routes/_authenticated.app.pools'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated.app.onboarding'
import { Route as AuthenticatedAppNftsRouteImport } from './routes/_authenticated.app.nfts'
import { Route as AuthenticatedAppLaunchesRouteImport } from './routes/_authenticated.app.launches'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated.app.history'
import { Route as AuthenticatedAppExploreRouteImport } from './routes/_authenticated.app.explore'
import { Route as AuthenticatedAppEarningsRouteImport } from './routes/_authenticated.app.earnings'
import { Route as AuthenticatedAppApiKeysRouteImport } from './routes/_authenticated.app.api-keys'
import { Route as AuthenticatedAppAirdropsRouteImport } from './routes/_authenticated.app.airdrops'
import { Route as AuthenticatedAppActionsRouteImport } from './routes/_authenticated.app.actions'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretpanelRoute = SecretpanelRouteImport.update({
  id: '/secretpanel',
  path: '/secretpanel',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesRoute = LaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsRoute = BugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentApiRoute = AgentApiRouteImport.update({
  id: '/agent-api',
  path: '/agent-api',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsIndexRoute = NftsIndexRouteImport.update({
  id: '/nfts/',
  path: '/nfts/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramVerifyRoute = TelegramVerifyRouteImport.update({
  id: '/telegram/verify',
  path: '/telegram/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramAuthRoute = TelegramAuthRouteImport.update({
  id: '/telegram/auth',
  path: '/telegram/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsAuthRoute = SmsAuthRouteImport.update({
  id: '/sms/auth',
  path: '/sms/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsCollectionIdRoute = NftsCollectionIdRouteImport.update({
  id: '/nfts/$collectionId',
  path: '/nfts/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinMintRoute = CoinMintRouteImport.update({
  id: '/coin/$mint',
  path: '/coin/$mint',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli/auth',
  path: '/cli/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBannedRoute = AuthBannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTerminalRoute = AuthenticatedTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWalletRoute = AuthenticatedAppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTerminalRoute =
  AuthenticatedAppTerminalRouteImport.update({
    id: '/terminal',
    path: '/terminal',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSchedulerRoute =
  AuthenticatedAppSchedulerRouteImport.update({
    id: '/scheduler',
    path: '/scheduler',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPoolsRoute = AuthenticatedAppPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNftsRoute = AuthenticatedAppNftsRouteImport.update({
  id: '/nfts',
  path: '/nfts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLaunchesRoute =
  AuthenticatedAppLaunchesRouteImport.update({
    id: '/launches',
    path: '/launches',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppExploreRoute = AuthenticatedAppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEarningsRoute =
  AuthenticatedAppEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppApiKeysRoute = AuthenticatedAppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAirdropsRoute =
  AuthenticatedAppAirdropsRouteImport.update({
    id: '/airdrops',
    path: '/airdrops',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppActionsRoute = AuthenticatedAppActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent-api': typeof AgentApiRoute
  '/auth': typeof AuthRouteWithChildren
  '/bugs': typeof BugsRoute
  '/docs': typeof DocsRoute
  '/explore': typeof ExploreRoute
  '/launch': typeof LaunchRoute
  '/launches': typeof LaunchesRoute
  '/links': typeof LinksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/secretpanel': typeof SecretpanelRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/terminal': typeof AuthenticatedTerminalRoute
  '/auth/banned': typeof AuthBannedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cli/auth': typeof CliAuthRoute
  '/coin/$mint': typeof CoinMintRoute
  '/nfts/$collectionId': typeof NftsCollectionIdRoute
  '/sms/auth': typeof SmsAuthRoute
  '/telegram/auth': typeof TelegramAuthRoute
  '/telegram/verify': typeof TelegramVerifyRoute
  '/u/$username': typeof UUsernameRoute
  '/nfts/': typeof NftsIndexRoute
  '/app/actions': typeof AuthenticatedAppActionsRoute
  '/app/airdrops': typeof AuthenticatedAppAirdropsRoute
  '/app/api-keys': typeof AuthenticatedAppApiKeysRoute
  '/app/earnings': typeof AuthenticatedAppEarningsRoute
  '/app/explore': typeof AuthenticatedAppExploreRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/launches': typeof AuthenticatedAppLaunchesRoute
  '/app/nfts': typeof AuthenticatedAppNftsRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/pools': typeof AuthenticatedAppPoolsRoute
  '/app/scheduler': typeof AuthenticatedAppSchedulerRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/terminal': typeof AuthenticatedAppTerminalRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent-api': typeof AgentApiRoute
  '/auth': typeof AuthRouteWithChildren
  '/bugs': typeof BugsRoute
  '/docs': typeof DocsRoute
  '/explore': typeof ExploreRoute
  '/launch': typeof LaunchRoute
  '/launches': typeof LaunchesRoute
  '/links': typeof LinksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/secretpanel': typeof SecretpanelRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/terminal': typeof AuthenticatedTerminalRoute
  '/auth/banned': typeof AuthBannedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cli/auth': typeof CliAuthRoute
  '/coin/$mint': typeof CoinMintRoute
  '/nfts/$collectionId': typeof NftsCollectionIdRoute
  '/sms/auth': typeof SmsAuthRoute
  '/telegram/auth': typeof TelegramAuthRoute
  '/telegram/verify': typeof TelegramVerifyRoute
  '/u/$username': typeof UUsernameRoute
  '/nfts': typeof NftsIndexRoute
  '/app/actions': typeof AuthenticatedAppActionsRoute
  '/app/airdrops': typeof AuthenticatedAppAirdropsRoute
  '/app/api-keys': typeof AuthenticatedAppApiKeysRoute
  '/app/earnings': typeof AuthenticatedAppEarningsRoute
  '/app/explore': typeof AuthenticatedAppExploreRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/launches': typeof AuthenticatedAppLaunchesRoute
  '/app/nfts': typeof AuthenticatedAppNftsRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/pools': typeof AuthenticatedAppPoolsRoute
  '/app/scheduler': typeof AuthenticatedAppSchedulerRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/terminal': typeof AuthenticatedAppTerminalRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/activity': typeof ActivityRoute
  '/agent-api': typeof AgentApiRoute
  '/auth': typeof AuthRouteWithChildren
  '/bugs': typeof BugsRoute
  '/docs': typeof DocsRoute
  '/explore': typeof ExploreRoute
  '/launch': typeof LaunchRoute
  '/launches': typeof LaunchesRoute
  '/links': typeof LinksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/secretpanel': typeof SecretpanelRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/terminal': typeof AuthenticatedTerminalRoute
  '/auth/banned': typeof AuthBannedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cli/auth': typeof CliAuthRoute
  '/coin/$mint': typeof CoinMintRoute
  '/nfts/$collectionId': typeof NftsCollectionIdRoute
  '/sms/auth': typeof SmsAuthRoute
  '/telegram/auth': typeof TelegramAuthRoute
  '/telegram/verify': typeof TelegramVerifyRoute
  '/u/$username': typeof UUsernameRoute
  '/nfts/': typeof NftsIndexRoute
  '/_authenticated/app/actions': typeof AuthenticatedAppActionsRoute
  '/_authenticated/app/airdrops': typeof AuthenticatedAppAirdropsRoute
  '/_authenticated/app/api-keys': typeof AuthenticatedAppApiKeysRoute
  '/_authenticated/app/earnings': typeof AuthenticatedAppEarningsRoute
  '/_authenticated/app/explore': typeof AuthenticatedAppExploreRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/app/launches': typeof AuthenticatedAppLaunchesRoute
  '/_authenticated/app/nfts': typeof AuthenticatedAppNftsRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/pools': typeof AuthenticatedAppPoolsRoute
  '/_authenticated/app/scheduler': typeof AuthenticatedAppSchedulerRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/terminal': typeof AuthenticatedAppTerminalRoute
  '/_authenticated/app/wallet': typeof AuthenticatedAppWalletRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agent-api'
    | '/auth'
    | '/bugs'
    | '/docs'
    | '/explore'
    | '/launch'
    | '/launches'
    | '/links'
    | '/privacy-policy'
    | '/secretpanel'
    | '/terms-of-service'
    | '/app'
    | '/terminal'
    | '/auth/banned'
    | '/auth/callback'
    | '/cli/auth'
    | '/coin/$mint'
    | '/nfts/$collectionId'
    | '/sms/auth'
    | '/telegram/auth'
    | '/telegram/verify'
    | '/u/$username'
    | '/nfts/'
    | '/app/actions'
    | '/app/airdrops'
    | '/app/api-keys'
    | '/app/earnings'
    | '/app/explore'
    | '/app/history'
    | '/app/launches'
    | '/app/nfts'
    | '/app/onboarding'
    | '/app/pools'
    | '/app/scheduler'
    | '/app/settings'
    | '/app/terminal'
    | '/app/wallet'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agent-api'
    | '/auth'
    | '/bugs'
    | '/docs'
    | '/explore'
    | '/launch'
    | '/launches'
    | '/links'
    | '/privacy-policy'
    | '/secretpanel'
    | '/terms-of-service'
    | '/terminal'
    | '/auth/banned'
    | '/auth/callback'
    | '/cli/auth'
    | '/coin/$mint'
    | '/nfts/$collectionId'
    | '/sms/auth'
    | '/telegram/auth'
    | '/telegram/verify'
    | '/u/$username'
    | '/nfts'
    | '/app/actions'
    | '/app/airdrops'
    | '/app/api-keys'
    | '/app/earnings'
    | '/app/explore'
    | '/app/history'
    | '/app/launches'
    | '/app/nfts'
    | '/app/onboarding'
    | '/app/pools'
    | '/app/scheduler'
    | '/app/settings'
    | '/app/terminal'
    | '/app/wallet'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activity'
    | '/agent-api'
    | '/auth'
    | '/bugs'
    | '/docs'
    | '/explore'
    | '/launch'
    | '/launches'
    | '/links'
    | '/privacy-policy'
    | '/secretpanel'
    | '/terms-of-service'
    | '/_authenticated/app'
    | '/_authenticated/terminal'
    | '/auth/banned'
    | '/auth/callback'
    | '/cli/auth'
    | '/coin/$mint'
    | '/nfts/$collectionId'
    | '/sms/auth'
    | '/telegram/auth'
    | '/telegram/verify'
    | '/u/$username'
    | '/nfts/'
    | '/_authenticated/app/actions'
    | '/_authenticated/app/airdrops'
    | '/_authenticated/app/api-keys'
    | '/_authenticated/app/earnings'
    | '/_authenticated/app/explore'
    | '/_authenticated/app/history'
    | '/_authenticated/app/launches'
    | '/_authenticated/app/nfts'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/pools'
    | '/_authenticated/app/scheduler'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/terminal'
    | '/_authenticated/app/wallet'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  AgentApiRoute: typeof AgentApiRoute
  AuthRoute: typeof AuthRouteWithChildren
  BugsRoute: typeof BugsRoute
  DocsRoute: typeof DocsRoute
  ExploreRoute: typeof ExploreRoute
  LaunchRoute: typeof LaunchRoute
  LaunchesRoute: typeof LaunchesRoute
  LinksRoute: typeof LinksRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SecretpanelRoute: typeof SecretpanelRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  CliAuthRoute: typeof CliAuthRoute
  CoinMintRoute: typeof CoinMintRoute
  NftsCollectionIdRoute: typeof NftsCollectionIdRoute
  SmsAuthRoute: typeof SmsAuthRoute
  TelegramAuthRoute: typeof TelegramAuthRoute
  TelegramVerifyRoute: typeof TelegramVerifyRoute
  UUsernameRoute: typeof UUsernameRoute
  NftsIndexRoute: typeof NftsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretpanel': {
      id: '/secretpanel'
      path: '/secretpanel'
      fullPath: '/secretpanel'
      preLoaderRoute: typeof SecretpanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches': {
      id: '/launches'
      path: '/launches'
      fullPath: '/launches'
      preLoaderRoute: typeof LaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs': {
      id: '/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof BugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-api': {
      id: '/agent-api'
      path: '/agent-api'
      fullPath: '/agent-api'
      preLoaderRoute: typeof AgentApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts/': {
      id: '/nfts/'
      path: '/nfts'
      fullPath: '/nfts/'
      preLoaderRoute: typeof NftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram/verify': {
      id: '/telegram/verify'
      path: '/telegram/verify'
      fullPath: '/telegram/verify'
      preLoaderRoute: typeof TelegramVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram/auth': {
      id: '/telegram/auth'
      path: '/telegram/auth'
      fullPath: '/telegram/auth'
      preLoaderRoute: typeof TelegramAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms/auth': {
      id: '/sms/auth'
      path: '/sms/auth'
      fullPath: '/sms/auth'
      preLoaderRoute: typeof SmsAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts/$collectionId': {
      id: '/nfts/$collectionId'
      path: '/nfts/$collectionId'
      fullPath: '/nfts/$collectionId'
      preLoaderRoute: typeof NftsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin/$mint': {
      id: '/coin/$mint'
      path: '/coin/$mint'
      fullPath: '/coin/$mint'
      preLoaderRoute: typeof CoinMintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/auth': {
      id: '/cli/auth'
      path: '/cli/auth'
      fullPath: '/cli/auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/banned': {
      id: '/auth/banned'
      path: '/banned'
      fullPath: '/auth/banned'
      preLoaderRoute: typeof AuthBannedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/terminal': {
      id: '/_authenticated/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AuthenticatedTerminalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/wallet': {
      id: '/_authenticated/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AuthenticatedAppWalletRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/terminal': {
      id: '/_authenticated/app/terminal'
      path: '/terminal'
      fullPath: '/app/terminal'
      preLoaderRoute: typeof AuthenticatedAppTerminalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scheduler': {
      id: '/_authenticated/app/scheduler'
      path: '/scheduler'
      fullPath: '/app/scheduler'
      preLoaderRoute: typeof AuthenticatedAppSchedulerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pools': {
      id: '/_authenticated/app/pools'
      path: '/pools'
      fullPath: '/app/pools'
      preLoaderRoute: typeof AuthenticatedAppPoolsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/nfts': {
      id: '/_authenticated/app/nfts'
      path: '/nfts'
      fullPath: '/app/nfts'
      preLoaderRoute: typeof AuthenticatedAppNftsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/launches': {
      id: '/_authenticated/app/launches'
      path: '/launches'
      fullPath: '/app/launches'
      preLoaderRoute: typeof AuthenticatedAppLaunchesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/explore': {
      id: '/_authenticated/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AuthenticatedAppExploreRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/earnings': {
      id: '/_authenticated/app/earnings'
      path: '/earnings'
      fullPath: '/app/earnings'
      preLoaderRoute: typeof AuthenticatedAppEarningsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/api-keys': {
      id: '/_authenticated/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AuthenticatedAppApiKeysRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/airdrops': {
      id: '/_authenticated/app/airdrops'
      path: '/airdrops'
      fullPath: '/app/airdrops'
      preLoaderRoute: typeof AuthenticatedAppAirdropsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/actions': {
      id: '/_authenticated/app/actions'
      path: '/actions'
      fullPath: '/app/actions'
      preLoaderRoute: typeof AuthenticatedAppActionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActionsRoute: typeof AuthenticatedAppActionsRoute
  AuthenticatedAppAirdropsRoute: typeof AuthenticatedAppAirdropsRoute
  AuthenticatedAppApiKeysRoute: typeof AuthenticatedAppApiKeysRoute
  AuthenticatedAppEarningsRoute: typeof AuthenticatedAppEarningsRoute
  AuthenticatedAppExploreRoute: typeof AuthenticatedAppExploreRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppLaunchesRoute: typeof AuthenticatedAppLaunchesRoute
  AuthenticatedAppNftsRoute: typeof AuthenticatedAppNftsRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppPoolsRoute: typeof AuthenticatedAppPoolsRoute
  AuthenticatedAppSchedulerRoute: typeof AuthenticatedAppSchedulerRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTerminalRoute: typeof AuthenticatedAppTerminalRoute
  AuthenticatedAppWalletRoute: typeof AuthenticatedAppWalletRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActionsRoute: AuthenticatedAppActionsRoute,
  AuthenticatedAppAirdropsRoute: AuthenticatedAppAirdropsRoute,
  AuthenticatedAppApiKeysRoute: AuthenticatedAppApiKeysRoute,
  AuthenticatedAppEarningsRoute: AuthenticatedAppEarningsRoute,
  AuthenticatedAppExploreRoute: AuthenticatedAppExploreRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppLaunchesRoute: AuthenticatedAppLaunchesRoute,
  AuthenticatedAppNftsRoute: AuthenticatedAppNftsRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppPoolsRoute: AuthenticatedAppPoolsRoute,
  AuthenticatedAppSchedulerRoute: AuthenticatedAppSchedulerRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTerminalRoute: AuthenticatedAppTerminalRoute,
  AuthenticatedAppWalletRoute: AuthenticatedAppWalletRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedTerminalRoute: typeof AuthenticatedTerminalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedTerminalRoute: AuthenticatedTerminalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthBannedRoute: typeof AuthBannedRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBannedRoute: AuthBannedRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ActivityRoute: ActivityRoute,
  AgentApiRoute: AgentApiRoute,
  AuthRoute: AuthRouteWithChildren,
  BugsRoute: BugsRoute,
  DocsRoute: DocsRoute,
  ExploreRoute: ExploreRoute,
  LaunchRoute: LaunchRoute,
  LaunchesRoute: LaunchesRoute,
  LinksRoute: LinksRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SecretpanelRoute: SecretpanelRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  CliAuthRoute: CliAuthRoute,
  CoinMintRoute: CoinMintRoute,
  NftsCollectionIdRoute: NftsCollectionIdRoute,
  SmsAuthRoute: SmsAuthRoute,
  TelegramAuthRoute: TelegramAuthRoute,
  TelegramVerifyRoute: TelegramVerifyRoute,
  UUsernameRoute: UUsernameRoute,
  NftsIndexRoute: NftsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
