-- Production backend hardening primitives.
-- This migration is intentionally additive and backwards compatible with the
-- currently deployed Edge Functions.

create table if not exists public.wallet_export_challenges (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  wallet_id uuid not null references public.wallets(id) on delete cascade,
  token_hash text not null unique,
  status text not null default 'pending',
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  constraint wallet_export_challenges_status_check
    check (status in ('pending', 'used', 'expired', 'cancelled'))
);

create index if not exists wallet_export_challenges_user_created_idx
  on public.wallet_export_challenges (user_id, created_at desc);
create index if not exists wallet_export_challenges_pending_expiry_idx
  on public.wallet_export_challenges (expires_at)
  where status = 'pending';

alter table public.wallet_export_challenges enable row level security;
revoke all on public.wallet_export_challenges from public, anon, authenticated;
grant all on public.wallet_export_challenges to service_role;

create table if not exists public.wallet_security_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  wallet_id uuid references public.wallets(id) on delete set null,
  event_type text not null,
  outcome text not null,
  request_ip text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists wallet_security_events_user_created_idx
  on public.wallet_security_events (user_id, created_at desc);
create index if not exists wallet_security_events_type_created_idx
  on public.wallet_security_events (event_type, created_at desc);

alter table public.wallet_security_events enable row level security;
revoke all on public.wallet_security_events from public, anon, authenticated;
grant all on public.wallet_security_events to service_role;
revoke all on sequence public.wallet_security_events_id_seq from public, anon, authenticated;
grant usage, select on sequence public.wallet_security_events_id_seq to service_role;

create table if not exists public.linkr_rate_limit_windows (
  subject_type text not null,
  subject_id text not null,
  window_seconds integer not null,
  window_start timestamptz not null,
  request_count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (subject_type, subject_id, window_seconds, window_start),
  constraint linkr_rate_limit_windows_seconds_check
    check (window_seconds between 1 and 86400),
  constraint linkr_rate_limit_windows_count_check
    check (request_count >= 0)
);

create index if not exists linkr_rate_limit_windows_expiry_idx
  on public.linkr_rate_limit_windows (window_start, window_seconds);

alter table public.linkr_rate_limit_windows enable row level security;
revoke all on public.linkr_rate_limit_windows from public, anon, authenticated;
grant all on public.linkr_rate_limit_windows to service_role;

create or replace function public.consume_linkr_rate_limit(
  p_subject_type text,
  p_subject_id text,
  p_window_seconds integer,
  p_limit integer
)
returns table (allowed boolean, remaining integer, reset_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_window_start timestamptz;
  v_count integer;
begin
  if p_limit <= 0 then
    return query select true, 2147483647, now();
    return;
  end if;
  if p_window_seconds < 1 or p_window_seconds > 86400 then
    raise exception 'invalid_rate_limit_window';
  end if;
  if nullif(btrim(p_subject_type), '') is null or nullif(btrim(p_subject_id), '') is null then
    raise exception 'invalid_rate_limit_subject';
  end if;

  v_window_start := to_timestamp(
    floor(extract(epoch from clock_timestamp()) / p_window_seconds) * p_window_seconds
  );

  -- Bound historical rows for active subjects without a global table scan on
  -- every request. The current and immediately previous windows are retained.
  delete from public.linkr_rate_limit_windows
  where subject_type = left(p_subject_type, 80)
    and subject_id = left(p_subject_id, 240)
    and window_seconds = p_window_seconds
    and window_start < v_window_start - make_interval(secs => p_window_seconds);

  insert into public.linkr_rate_limit_windows (
    subject_type,
    subject_id,
    window_seconds,
    window_start,
    request_count,
    updated_at
  ) values (
    left(p_subject_type, 80),
    left(p_subject_id, 240),
    p_window_seconds,
    v_window_start,
    1,
    now()
  )
  on conflict (subject_type, subject_id, window_seconds, window_start)
  do update set
    request_count = public.linkr_rate_limit_windows.request_count + 1,
    updated_at = now()
  where public.linkr_rate_limit_windows.request_count < p_limit
  returning request_count into v_count;

  if v_count is null then
    return query select false, 0, v_window_start + make_interval(secs => p_window_seconds);
  else
    return query select true, greatest(0, p_limit - v_count),
      v_window_start + make_interval(secs => p_window_seconds);
  end if;
end;
$$;

revoke all on function public.consume_linkr_rate_limit(text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_linkr_rate_limit(text, text, integer, integer)
  to service_role;

create or replace function public.acquire_linkr_agent_lock(
  p_lock_key text,
  p_user_id uuid,
  p_surface text,
  p_scope_type text,
  p_scope_id text,
  p_run_id uuid,
  p_owner_id text,
  p_expires_at timestamptz
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id text;
begin
  insert into public.linkr_agent_locks (
    lock_key,
    user_id,
    surface,
    scope_type,
    scope_id,
    run_id,
    owner_id,
    expires_at
  ) values (
    p_lock_key,
    p_user_id,
    p_surface,
    p_scope_type,
    p_scope_id,
    p_run_id,
    p_owner_id,
    p_expires_at
  )
  on conflict (lock_key)
  do update set
    user_id = excluded.user_id,
    surface = excluded.surface,
    scope_type = excluded.scope_type,
    scope_id = excluded.scope_id,
    run_id = excluded.run_id,
    owner_id = excluded.owner_id,
    expires_at = excluded.expires_at,
    updated_at = now()
  where public.linkr_agent_locks.expires_at < now()
  returning owner_id into v_owner_id;

  return v_owner_id = p_owner_id;
end;
$$;

revoke all on function public.acquire_linkr_agent_lock(text, uuid, text, text, text, uuid, text, timestamptz)
  from public, anon, authenticated;
grant execute on function public.acquire_linkr_agent_lock(text, uuid, text, text, text, uuid, text, timestamptz)
  to service_role;

create or replace function public.increment_linkr_terminal_message_count(
  p_conversation_id uuid,
  p_user_id uuid,
  p_delta integer,
  p_preview text default null,
  p_role text default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if p_delta < 0 or p_delta > 2 then
    raise exception 'invalid_message_count_delta';
  end if;

  update public.linkr_terminal_conversations
  set
    message_count = message_count + p_delta,
    last_message_preview = coalesce(left(p_preview, 180), last_message_preview),
    last_message_role = coalesce(p_role, last_message_role),
    last_message_at = case when p_preview is null then last_message_at else now() end
  where id = p_conversation_id
    and user_id = p_user_id
    and deleted_at is null
  returning message_count into v_count;

  if v_count is null then
    raise exception 'conversation_not_found';
  end if;
  return v_count;
end;
$$;

revoke all on function public.increment_linkr_terminal_message_count(uuid, uuid, integer, text, text)
  from public, anon, authenticated;
grant execute on function public.increment_linkr_terminal_message_count(uuid, uuid, integer, text, text)
  to service_role;

create or replace function public.search_linkr_user_memory(
  p_user_id uuid,
  p_query text,
  p_limit integer default 6
)
returns table (
  source_type text,
  source_id text,
  title text,
  searchable_text text,
  metadata jsonb,
  created_at timestamptz,
  rank real
)
language sql
stable
security definer
set search_path = public
as $$
  select
    umi.source_type,
    umi.source_id,
    umi.title,
    umi.searchable_text,
    umi.metadata,
    umi.created_at,
    ts_rank_cd(
      to_tsvector('english', umi.searchable_text),
      websearch_to_tsquery('english', left(coalesce(p_query, ''), 200))
    )::real as rank
  from public.user_memory_index umi
  where umi.user_id = p_user_id
    and nullif(btrim(coalesce(p_query, '')), '') is not null
    and to_tsvector('english', umi.searchable_text)
      @@ websearch_to_tsquery('english', left(coalesce(p_query, ''), 200))
  order by rank desc, umi.created_at desc
  limit least(greatest(coalesce(p_limit, 6), 1), 20);
$$;

revoke all on function public.search_linkr_user_memory(uuid, text, integer)
  from public, anon, authenticated;
grant execute on function public.search_linkr_user_memory(uuid, text, integer)
  to service_role;
